function plotHistogram(org, wb, final)
figure, imhist(org(:,:,1)),title('red channel')
figure, imhist(wb(:,:,1)),title('red channel')
figure, imhist(final(:,:,1)),title('red channel')
figure, imhist(org(:,:,2)),title('green channel')
figure, imhist(wb(:,:,2)),title('green channel')
figure, imhist(final(:,:,2)),title('green channel')
figure, imhist(org(:,:,3)),title('blue channel')
figure, imhist(wb(:,:,3)),title('blue channel')
figure, imhist(final(:,:,3)),title('blue channel')